### ISSUE TITLE
Paintings ++ stops the game from loading.

### ISSUE THREAD

**Issue by KirbyKid256** [AbsolemJackdaw/PaintingsFabric#1] opened 2021-08-19 12:55 UTC
Hi, I know this mod just came out for fabric, so things are subject for change, but this mod isn't loading on my computer and I don't know why.
[crash-2021-08-19_08.52.25-client.txt](https://github.com/ArtixAllMighty/PaintingsFabric/files/7014473/crash-2021-08-19_08.52.25-client.txt)

**Comment by AbsolemJackdaw** [comment] 2021-08-19 14:25
Hi !! thanks for the report ! 

I'm afraid this is yet another issue of JSON Syntax... This means that you _probably_ installed a custom painting pack, which contains a JSON file that has an syntax error. 

The log says : 
"Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 2 column 5 path $."

a) I'd go trough your json files and check them for errors, or report the maker of the pack of this error. 

b) It is also possible, because the mod scans all resourcepack files, that _A_ resourcepack file contains a faulty json. 
If you got access to other log files, there may be a detailed print about what files got accepted , and which rejected. 
The last file printed out (probably under "Candidate found + filename" should be the json file containing errors.

c) Feel free to post your logs here, or join our [discord](https://discord.gg/8MEdFZh) so we can go trough this step by step.

**Comment by AbsolemJackdaw** [comment] 2021-09-02 16:12
Case closed as resolved due to lack of a response.
version 1.0.0.1 equally has more aid in the logs for these errors now,
as well as better crash handling

**Closed as completed by AbsolemJackdaw** 2021-09-02 16:12 UTC
